import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Main from '../Components/Main'
import Box from '../Components/library/Box'

export default function Home() {
  return (
    <>
    
      <Head>
        <title>Shortly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <Box
    //width={['350px','1440p']}

    >
      <Main />
    </Box>
    
    
    
    </>
  )
}